Include storage access info in email after successfull start.

diff --git a/rootfs/etc/cont-init.d/20-00-mariadb b/rootfs/etc/cont-init.d/20-00-mariadb
--- a/rootfs/etc/cont-init.d/20-00-mariadb
+++ b/rootfs/etc/cont-init.d/20-00-mariadb
@@ -1,7 +1,14 @@
 #!/usr/bin/with-contenv sh
 
-# https://raw.githubusercontent.com/nimmis/docker-alpine-mariadb/master/root/etc/run_always/db_init
-# https://github.com/dockhippie/mariadb/blob/master/rootfs/etc/s6/mariadb/setup
+# Installation UUID must be informed
+if [ -z "$DASPANEL_SYS_UUID" ]; then
+    echo "***"
+    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
+    echo "***"
+    exit 1
+fi
+
+export DASPANEL_SYS_PASSWORD=`cat /opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json | /usr/bin/jq -r '.sys.password'`
 
 [[ -z "${MARIADB_DEFAULT_CHARACTER_SET}" ]] && export MARIADB_DEFAULT_CHARACTER_SET="utf8"
 [[ -z "${MARIADB_CHARACTER_SET_SERVER}" ]] && export MARIADB_CHARACTER_SET_SERVER="utf8"
@@ -28,18 +35,18 @@
 
 # Setup MySql root password == daspanel master password if not set using env variable
 if [ -z "$MARIADB_ROOT_PASSWORD" ]; then
-  MARIADB_ROOT_PASSWORD="$DASPANEL_MASTER_PASSWORD"
+  MARIADB_ROOT_PASSWORD="$DASPANEL_SYS_PASSWORD"
 fi 
 
-if [ ! -d "/opt/daspanel/data/$DASPANEL_GUUID/mysql" ]; then
-	mkdir -p /opt/daspanel/data/$DASPANEL_GUUID/mysql
+if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/mysql" ]; then
+	mkdir -p /opt/daspanel/data/$DASPANEL_SYS_UUID/mysql
 fi
-chown -R daspanel:daspanel /opt/daspanel/data/$DASPANEL_GUUID/mysql
+chown -R daspanel:daspanel /opt/daspanel/data/$DASPANEL_SYS_UUID/mysql
 
 if [ -d "/var/lib/mysql" ]; then
     rm -Rf /var/lib/mysql
 fi
-ln -sf /opt/daspanel/data/$DASPANEL_GUUID/mysql /var/lib/mysql
+ln -sf /opt/daspanel/data/$DASPANEL_SYS_UUID/mysql /var/lib/mysql
 chown -R daspanel:daspanel /var/lib/mysql
 
 if [ ! -d "/var/run/mysqld" ]; then
@@ -56,7 +63,7 @@ chown -R daspanel:daspanel /var/log/mysql
   -o /etc/mysql/my.cnf \
   /opt/daspanel/conf-templates/etc/mysql/my.cnf.tmpl
 
-if [ -f /opt/daspanel/data/$DASPANEL_GUUID/containers/mysql.configured ]; then
+if [ -f /opt/daspanel/data/$DASPANEL_SYS_UUID/containers/mysql.configured ]; then
   exit 0
 fi
 
@@ -190,11 +197,11 @@ fi
 echo "daspanel-mariadb: Mark mariadb as configured"
 
 # Save details about configuration for late use
-if [ ! -d "/opt/daspanel/data/$DASPANEL_GUUID/containers" ]; then
-	mkdir -p /opt/daspanel/data/$DASPANEL_GUUID/containers
+if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/containers" ]; then
+	mkdir -p /opt/daspanel/data/$DASPANEL_SYS_UUID/containers
 fi
 
-touch /opt/daspanel/data/$DASPANEL_GUUID/containers/mysql.configured
+touch /opt/daspanel/data/$DASPANEL_SYS_UUID/containers/mysql.configured
 { 
     echo ""; 
     echo ""; 
@@ -213,7 +220,7 @@ touch /opt/daspanel/data/$DASPANEL_GUUID/containers/mysql.configured
     fi
     echo ""; 
     echo ""; 
-} > /opt/daspanel/data/$DASPANEL_GUUID/containers/mysql.configured
+} > /opt/daspanel/data/$DASPANEL_SYS_UUID/containers/mysql.configured
 
 # secure daspanel
 chown -R daspanel:daspanel /opt/daspanel/data
